# Generated by Django 6.0.1 on 2026-02-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_likes_alter_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinfo',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
