# Generated by Django 6.0.1 on 2026-02-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(null=True, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_type', models.CharField(max_length=200)),
                ('screen_resolution', models.CharField(max_length=20)),
                ('ram', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('camera', models.PositiveIntegerField()),
                ('battery', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
